# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bhamdi <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/12/03 22:19:58 by bhamdi            #+#    #+#              #
#    Updated: 2016/12/03 22:20:24 by bhamdi           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRC = main.c

all: $(NAME)

$(NAME) :
		gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:

fclean: clean
		/bin/rm -rf $(NAME)

re: fclean all
